service:
  name: coins-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: "ap-south-1"
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
    - ${file(iam/SendMailIAM.yml):SendMailIAM}
resources:
  Resources:
    CoinsBufferTable: ${file(resources/CoinsBufferTable.yml):CoinsBufferTable}
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}
    CoinsTable: ${file(resources/CoinsTable.yml):CoinsTable}
    CoinsRedemptionQueue: ${file(resources/CoinsRedemptionQueue.yml):CoinsRedemptionQueue}
functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /user
  getUsers:
    handler: src/handlers/getUsers.handler
    events:
      - http:
          method: GET
          path: /users
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - http:
          method: GET
          path: /user/{user_id}
  UpdateCoins:
    handler: src/handlers/UpdateCoins.handler
    events:
      - http:
          method: PATCH
          path: /user/{user_id}
  coinsRedeem:
    handler: src/handlers/coinsRedeem.handler
    events:
      - http:
          method: POST
          path: /coinsredeem
  processBufferItems:
    handler: src/handlers/processBufferItems.handler
    events:
      - schedule: rate(5 minutes)
  processRedemptionQueue:
    handler: src/handlers/processRedemptionQueue.handler
    events:
      - sqs:
          arn: ${self:custom.coinsRedemptionQueue.arn}
          batchSize: 10
          maximumRetryAttempts: 10
  createBufferRecord:
    handler: src/handlers/createBufferRecord.handler
    events:
      - http:
          method: POST
          path: /buffer
  sendMail:
    handler: src/handlers/sendMail.handler

custom:
  coinsRedemptionQueue:
    arn: !GetAtt CoinsRedemptionQueue.Arn
