service:
  name: coins-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: "ap-south-1"
  iamRoleStatements:
    - ${file(iam/CoinsTableIAM.yml):CoinsTableIAM}
resources:
  Resources:
    CoinsTable: ${file(resources/CoinsTable.yml):CoinsTable}
functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /user
  getUsers:
    handler: src/handlers/getUsers.handler
    events:
      - http:
          method: GET
          path: /users
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - http:
          method: GET
          path: /user/{user_id}
