CoinsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CoinsTable
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
