CoinsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CoinsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
